from __future__ import annotations

import asyncio
import json
import logging
import os
import tempfile
import urllib.parse
import uuid
from html.parser import HTMLParser
from pathlib import Path
from typing import Any

import asyncpg
import httpx
import pandas as pd
from fastapi import APIRouter, Depends, HTTPException, Path as ApiPath, Query
from fastapi.responses import FileResponse
from pandas.errors import ParserError

from rest_server.database import get_pool
from rest_server.deps import require_admin_actor
from rest_server.ingestion_models import (
    AIValidationResult,
    ArtifactReviewRequest,
    DatasheetDraftModel,
    IngestionArtifactDetail,
    IngestionArtifactSummary,
    ScrapeRequest,
    ScraperJobDetail,
    ScraperJobSummary,
)
from rest_server.patra_agent_service import (
    DEFAULT_LLM_API_BASE,
    DEFAULT_LLM_API_KEY,
    DEFAULT_LLM_MODEL,
)

log = logging.getLogger(__name__)
router = APIRouter(prefix="/api/ingestion", tags=["automated-ingestion"])

MIN_FILE_BYTES = int(os.getenv("INGESTION_MIN_FILE_BYTES", "1024") or "1024")
MAX_FILE_BYTES = int(os.getenv("INGESTION_MAX_FILE_BYTES", str(500 * 1024 * 1024)) or str(500 * 1024 * 1024))
DEFAULT_LLM_TIMEOUT = int(os.getenv("PATRA_AGENT_LLM_TIMEOUT_SECONDS", "60") or "60")
INGESTION_STAGING_DIR = Path(os.getenv("INGESTION_STAGING_DIR", "/data/ingestion-staging")).resolve()
INGESTION_LLM_API_BASE = os.getenv("INGESTION_LLM_API_BASE", DEFAULT_LLM_API_BASE)
INGESTION_LLM_MODEL = os.getenv("INGESTION_LLM_MODEL", "").strip()
INGESTION_LLM_API_KEY = os.getenv("INGESTION_LLM_API_KEY", DEFAULT_LLM_API_KEY)
INGESTION_LLM_ENABLED = os.getenv("INGESTION_LLM_ENABLED", "true").strip().lower() == "true"
INGESTION_LLM_FALLBACK_TO_CODE = os.getenv("INGESTION_LLM_FALLBACK_TO_CODE", "true").strip().lower() == "true"

ACTIVE_INGESTION_TASKS: dict[int, asyncio.Task] = {}

DEFAULT_TARGET_SCHEMA = {
    "title": "Human-readable dataset/resource title",
    "description": "Short description of what the CSV contains and why it matters",
    "resource_type": "Dataset-like resource classification",
    "creators": "Likely creators or authors derived from page context",
    "subjects": "Keywords or topical subjects",
    "publisher": "Likely publisher or source organization",
    "license_guess": "Most likely license or usage constraint",
    "related_download_url": "Direct CSV or related download URL",
}


SCRAPER_JOBS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS scraper_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_url text NOT NULL,
  requested_by text,
  status text NOT NULL,
  page_title text,
  discovered_csv_urls jsonb NOT NULL DEFAULT '[]'::jsonb,
  discovered_csv_count integer NOT NULL DEFAULT 0,
  processed_csv_count integer NOT NULL DEFAULT 0,
  passed_csv_count integer NOT NULL DEFAULT 0,
  created_artifact_count integer NOT NULL DEFAULT 0,
  recent_failures jsonb NOT NULL DEFAULT '[]'::jsonb,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  completed_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_scraper_jobs_status ON scraper_jobs (status);
CREATE INDEX IF NOT EXISTS idx_scraper_jobs_created_at ON scraper_jobs (created_at DESC);
"""


INGESTION_ARTIFACTS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS automated_ingestion_artifacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id bigint NOT NULL REFERENCES scraper_jobs(id) ON DELETE CASCADE,
  source_url text NOT NULL,
  page_title text,
  csv_url text NOT NULL,
  status text NOT NULL DEFAULT 'pending_review',
  headers_sample jsonb NOT NULL DEFAULT '[]'::jsonb,
  rows_sample jsonb NOT NULL DEFAULT '[]'::jsonb,
  validation_result jsonb NOT NULL,
  datasheet_draft jsonb NOT NULL,
  staged_csv_path text NOT NULL,
  staged_schema_path text NOT NULL,
  created_by text,
  reviewed_by text,
  reviewed_at timestamptz,
  review_notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_automated_ingestion_artifacts_job_id ON automated_ingestion_artifacts (job_id);
CREATE INDEX IF NOT EXISTS idx_automated_ingestion_artifacts_status ON automated_ingestion_artifacts (status);
CREATE INDEX IF NOT EXISTS idx_automated_ingestion_artifacts_created_at ON automated_ingestion_artifacts (created_at DESC);
"""


class CsvLinkParser(HTMLParser):
    def __init__(self, base_url: str) -> None:
        super().__init__()
        self.base_url = base_url
        self.page_title = ""
        self._inside_title = False
        self._title_chunks: list[str] = []
        self.csv_urls: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        lowered = tag.lower()
        attrs_dict = {key.lower(): value for key, value in attrs}
        if lowered == "title":
            self._inside_title = True
            self._title_chunks = []
            return
        if lowered != "a":
            return
        href = attrs_dict.get("href")
        if not href:
            return
        resolved = urllib.parse.urljoin(self.base_url, href)
        parsed = urllib.parse.urlparse(resolved)
        if parsed.scheme not in {"http", "https"}:
            return
        if parsed.path.lower().endswith(".csv") or ".csv" in resolved.lower():
            self.csv_urls.append(resolved)

    def handle_endtag(self, tag: str) -> None:
        if tag.lower() == "title" and self._inside_title:
            self._inside_title = False
            self.page_title = " ".join("".join(self._title_chunks).split()).strip()

    def handle_data(self, data: str) -> None:
        if self._inside_title:
            self._title_chunks.append(data)


async def _ensure_tables(conn: asyncpg.Connection) -> None:
    await conn.execute(SCRAPER_JOBS_TABLE_SQL)
    await conn.execute(INGESTION_ARTIFACTS_TABLE_SQL)


def _decode_json_column(value):
    if isinstance(value, str):
        return json.loads(value)
    return value


def _job_row_to_model(row: asyncpg.Record) -> ScraperJobDetail:
    return ScraperJobDetail(
        id=int(row["id"]),
        source_url=row["source_url"],
        status=row["status"],
        requested_by=row["requested_by"],
        page_title=row["page_title"],
        discovered_csv_count=int(row["discovered_csv_count"] or 0),
        processed_csv_count=int(row["processed_csv_count"] or 0),
        passed_csv_count=int(row["passed_csv_count"] or 0),
        created_artifact_count=int(row["created_artifact_count"] or 0),
        error_message=row["error_message"],
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
        completed_at=str(row["completed_at"]) if row["completed_at"] else None,
        discovered_csv_urls=_decode_json_column(row["discovered_csv_urls"]) or [],
        recent_failures=_decode_json_column(row["recent_failures"]) or [],
    )


def _artifact_row_to_summary(row: asyncpg.Record) -> IngestionArtifactSummary:
    draft = _decode_json_column(row["datasheet_draft"]) or {}
    return IngestionArtifactSummary(
        id=int(row["id"]),
        job_id=int(row["job_id"]),
        source_url=row["source_url"],
        page_title=row["page_title"],
        csv_url=row["csv_url"],
        status=row["status"],
        title=draft.get("title") or "Untitled resource",
        created_by=row["created_by"],
        reviewed_by=row["reviewed_by"],
        review_notes=row["review_notes"],
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
        reviewed_at=str(row["reviewed_at"]) if row["reviewed_at"] else None,
    )


def _artifact_row_to_detail(row: asyncpg.Record) -> IngestionArtifactDetail:
    summary = _artifact_row_to_summary(row)
    validation = AIValidationResult.model_validate(_decode_json_column(row["validation_result"]) or {})
    draft = DatasheetDraftModel.model_validate(_decode_json_column(row["datasheet_draft"]) or {})
    return IngestionArtifactDetail(
        **summary.model_dump(),
        headers_sample=_decode_json_column(row["headers_sample"]) or [],
        rows_sample=_decode_json_column(row["rows_sample"]) or [],
        validation_result=validation,
        datasheet_draft=draft,
        staged_csv_download_url=f"/api/ingestion/artifacts/{int(row['id'])}/download.csv",
        staged_schema_download_url=f"/api/ingestion/artifacts/{int(row['id'])}/download-schema",
        staged_csv_path=row["staged_csv_path"],
        staged_schema_path=row["staged_schema_path"],
    )


async def _insert_job(conn: asyncpg.Connection, source_url: str, requested_by: str | None) -> int:
    await _ensure_tables(conn)
    return int(
        await conn.fetchval(
            """
            INSERT INTO scraper_jobs (source_url, requested_by, status)
            VALUES ($1, $2, 'Pending')
            RETURNING id
            """,
            source_url,
            requested_by,
        )
    )


async def _update_job(
    conn: asyncpg.Connection,
    job_id: int,
    *,
    status: str | None = None,
    page_title: str | None = None,
    discovered_csv_urls: list[str] | None = None,
    discovered_csv_count: int | None = None,
    processed_csv_count: int | None = None,
    passed_csv_count: int | None = None,
    created_artifact_count: int | None = None,
    recent_failures: list[str] | None = None,
    error_message: str | None = None,
    completed: bool = False,
) -> None:
    assignments: list[str] = ["updated_at = NOW()"]
    params: list[Any] = [job_id]
    if status is not None:
        assignments.append(f"status = ${len(params) + 1}")
        params.append(status)
    if page_title is not None:
        assignments.append(f"page_title = ${len(params) + 1}")
        params.append(page_title)
    if discovered_csv_urls is not None:
        assignments.append(f"discovered_csv_urls = ${len(params) + 1}::jsonb")
        params.append(json.dumps(discovered_csv_urls))
    if discovered_csv_count is not None:
        assignments.append(f"discovered_csv_count = ${len(params) + 1}")
        params.append(discovered_csv_count)
    if processed_csv_count is not None:
        assignments.append(f"processed_csv_count = ${len(params) + 1}")
        params.append(processed_csv_count)
    if passed_csv_count is not None:
        assignments.append(f"passed_csv_count = ${len(params) + 1}")
        params.append(passed_csv_count)
    if created_artifact_count is not None:
        assignments.append(f"created_artifact_count = ${len(params) + 1}")
        params.append(created_artifact_count)
    if recent_failures is not None:
        assignments.append(f"recent_failures = ${len(params) + 1}::jsonb")
        params.append(json.dumps(recent_failures))
    if error_message is not None:
        assignments.append(f"error_message = ${len(params) + 1}")
        params.append(error_message)
    if completed:
        assignments.append("completed_at = NOW()")
    query = f"UPDATE scraper_jobs SET {', '.join(assignments)} WHERE id = $1"
    await conn.execute(query, *params)


async def _insert_artifact(
    conn: asyncpg.Connection,
    *,
    job_id: int,
    source_url: str,
    page_title: str | None,
    csv_url: str,
    headers_sample: list[str],
    rows_sample: list[dict[str, Any]],
    validation_result: AIValidationResult,
    datasheet_draft: DatasheetDraftModel,
    staged_csv_path: str,
    staged_schema_path: str,
    created_by: str | None,
) -> int:
    await _ensure_tables(conn)
    return int(
        await conn.fetchval(
            """
            INSERT INTO automated_ingestion_artifacts (
                job_id, source_url, page_title, csv_url, status, headers_sample, rows_sample,
                validation_result, datasheet_draft, staged_csv_path, staged_schema_path, created_by
            )
            VALUES (
                $1, $2, $3, $4, 'pending_review', $5::jsonb, $6::jsonb,
                $7::jsonb, $8::jsonb, $9, $10, $11
            )
            RETURNING id
            """,
            job_id,
            source_url,
            page_title,
            csv_url,
            json.dumps(headers_sample),
            json.dumps(rows_sample),
            json.dumps(validation_result.model_dump(by_alias=True)),
            json.dumps(datasheet_draft.model_dump()),
            staged_csv_path,
            staged_schema_path,
            created_by,
        )
    )


async def _fetch_job(conn: asyncpg.Connection, job_id: int) -> ScraperJobDetail | None:
    await _ensure_tables(conn)
    row = await conn.fetchrow("SELECT * FROM scraper_jobs WHERE id = $1", job_id)
    return _job_row_to_model(row) if row else None


def _validation_json_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "pass": {"type": "boolean"},
            "confidence": {"type": "number"},
            "resource_type": {"type": ["string", "null"]},
            "field_mappings": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "source_header": {"type": "string"},
                        "target_field": {"type": "string"},
                        "rationale": {"type": "string"},
                    },
                    "required": ["source_header", "target_field", "rationale"],
                },
            },
            "summary": {"type": "string"},
            "license_guess": {"type": ["string", "null"]},
            "recommended_title": {"type": ["string", "null"]},
            "reject_reasons": {"type": "array", "items": {"type": "string"}},
        },
        "required": [
            "pass",
            "confidence",
            "resource_type",
            "field_mappings",
            "summary",
            "license_guess",
            "recommended_title",
            "reject_reasons",
        ],
    }


def _draft_json_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "title": {"type": "string"},
            "description": {"type": "string"},
            "resource_type": {"type": "string"},
            "creators": {"type": "array", "items": {"type": "string"}},
            "subjects": {"type": "array", "items": {"type": "string"}},
            "publisher": {"type": ["string", "null"]},
            "license_guess": {"type": ["string", "null"]},
            "potential_uses": {"type": "array", "items": {"type": "string"}},
            "related_download_url": {"type": ["string", "null"]},
            "sample_notes": {"type": "array", "items": {"type": "string"}},
        },
        "required": [
            "title",
            "description",
            "resource_type",
            "creators",
            "subjects",
            "publisher",
            "license_guess",
            "potential_uses",
            "related_download_url",
            "sample_notes",
        ],
    }


def _extract_json(content: str) -> dict[str, Any]:
    content = content.strip()
    if content.startswith("{") and content.endswith("}"):
        return json.loads(content)
    start = content.find("{")
    end = content.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError(f"Model did not return JSON: {content[:200]}")
    return json.loads(content[start : end + 1])


def _build_chat_completions_url(api_base: str) -> str:
    base = (api_base or "").rstrip("/")
    if base.endswith("/chat/completions"):
        return base
    if base.endswith("/v1"):
        return f"{base}/chat/completions"
    return f"{base}/v1/chat/completions"


def _build_models_url(api_base: str) -> str:
    base = (api_base or "").rstrip("/")
    if base.endswith("/models"):
        return base
    if base.endswith("/v1"):
        return f"{base}/models"
    return f"{base}/v1/models"


def _extract_message_text(message: Any) -> str:
    if isinstance(message, str):
        return message
    if isinstance(message, list):
        parts: list[str] = []
        for item in message:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                text = item.get("text") or item.get("content") or ""
                if isinstance(text, str):
                    parts.append(text)
        return "\n".join(part for part in parts if part).strip()
    if isinstance(message, dict):
        text = message.get("text") or message.get("content") or ""
        return text if isinstance(text, str) else ""
    return ""


def _is_generation_model(model_id: str) -> bool:
    lowered = model_id.lower()
    return not any(token in lowered for token in ("embed", "embedding", "rerank", "moderation", "whisper", "tts"))


def _model_priority(model_id: str) -> tuple[int, str]:
    lowered = model_id.lower()
    if "gemma" in lowered:
        return (0, lowered)
    if "qwen" in lowered:
        return (1, lowered)
    if "glm" in lowered:
        return (2, lowered)
    return (3, lowered)


def _list_available_models(
    *,
    api_base: str,
    api_key: str,
    timeout_seconds: int = 10,
) -> list[str]:
    headers = {}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    with httpx.Client(timeout=timeout_seconds) as client:
        response = client.get(_build_models_url(api_base), headers=headers)
        response.raise_for_status()
        payload = response.json()
    models: list[str] = []
    for item in payload.get("data", []):
        model_id = item.get("id")
        if isinstance(model_id, str) and model_id.strip() and _is_generation_model(model_id):
            models.append(model_id.strip())
    return sorted(dict.fromkeys(models), key=_model_priority)


def _call_llm_json(
    *,
    prompt: str,
    schema_name: str,
    schema: dict[str, Any],
    api_base: str = DEFAULT_LLM_API_BASE,
    model: str = DEFAULT_LLM_MODEL,
    api_key: str = DEFAULT_LLM_API_KEY,
    timeout_seconds: int = DEFAULT_LLM_TIMEOUT,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "model": model,
        "temperature": 0.2,
        "top_p": 0.8,
        "presence_penalty": 0.5,
        "max_tokens": 1400,
        "chat_template_kwargs": {"enable_thinking": False},
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a PATRA data-ingestion validation agent. "
                    "Return strict JSON only. Do not include markdown, reasoning trace, or commentary."
                ),
            },
            {"role": "user", "content": prompt},
        ],
    }
    payload_with_schema = {
        **payload,
        "response_format": {
            "type": "json_schema",
            "json_schema": {
                "name": schema_name,
                "schema": schema,
            },
        },
    }
    headers = {
        "Content-Type": "application/json",
    }
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    with httpx.Client(timeout=timeout_seconds) as client:
        url = _build_chat_completions_url(api_base)
        try:
            response = client.post(
                url,
                headers=headers,
                json=payload_with_schema,
            )
            response.raise_for_status()
            parsed = response.json()
        except httpx.HTTPStatusError as exc:
            if exc.response.status_code != 400:
                raise
            response = client.post(
                url,
                headers=headers,
                json=payload,
            )
            response.raise_for_status()
            parsed = response.json()
    message = parsed["choices"][0]["message"]
    content = _extract_message_text(message.get("content"))
    if not content:
        reasoning = _extract_message_text(message.get("reasoning_content"))
        if reasoning:
            try:
                return _extract_json(reasoning)
            except Exception:
                pass
        raise ValueError(f"Model did not return JSON content. reasoning_content={reasoning[:400]}")
    try:
        return _extract_json(content)
    except Exception:
        reasoning = _extract_message_text(message.get("reasoning_content"))
        if reasoning:
            return _extract_json(reasoning)
        raise


def _call_llm_json_with_model_fallback(
    *,
    prompt: str,
    schema_name: str,
    schema: dict[str, Any],
    api_base: str,
    model: str | None,
    api_key: str,
    timeout_seconds: int = DEFAULT_LLM_TIMEOUT,
) -> dict[str, Any]:
    attempted: list[str] = []
    if model:
        candidate_models = [model]
    else:
        discovered = _list_available_models(api_base=api_base, api_key=api_key, timeout_seconds=min(timeout_seconds, 10))
        candidate_models = discovered or [DEFAULT_LLM_MODEL]

    last_exc: Exception | None = None
    for candidate in candidate_models:
        attempted.append(candidate)
        try:
            return _call_llm_json(
                prompt=prompt,
                schema_name=schema_name,
                schema=schema,
                api_base=api_base,
                model=candidate,
                api_key=api_key,
                timeout_seconds=timeout_seconds,
            )
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            log.warning("Ingestion LLM attempt failed for model %s: %s", candidate, exc)
            continue
    attempted_label = ", ".join(attempted) or "(none)"
    if last_exc:
        raise RuntimeError(f"All ingestion LLM attempts failed. attempted_models=[{attempted_label}] last_error={last_exc}") from last_exc
    raise RuntimeError(f"No ingestion LLM models available. attempted_models=[{attempted_label}]")


def _tokenize_header(value: str) -> set[str]:
    raw = "".join(ch.lower() if ch.isalnum() else " " for ch in str(value))
    return {token for token in raw.split() if token}


def _infer_header_mappings(headers: list[str], target_schema: dict[str, Any]) -> list[dict[str, str]]:
    mappings: list[dict[str, str]] = []
    target_fields = list(target_schema.keys())
    for header in headers:
        header_tokens = _tokenize_header(header)
        best_target = None
        best_score = 0
        for target in target_fields:
            target_tokens = _tokenize_header(target)
            overlap = len(header_tokens & target_tokens)
            if overlap > best_score:
                best_target = target
                best_score = overlap
        if best_target and best_score > 0:
            mappings.append(
                {
                    "source_header": header,
                    "target_field": best_target,
                    "rationale": "Deterministic token overlap between CSV header and PATRA target field.",
                }
            )
    return mappings


def _infer_resource_type(headers: list[str], rows: list[dict[str, Any]]) -> str:
    lowered = " ".join(headers).lower()
    if any(token in lowered for token in ("image", "label", "class", "target")):
        return "annotated_dataset"
    if any(token in lowered for token in ("lat", "lon", "longitude", "latitude", "geo")):
        return "geospatial_dataset"
    if any(token in lowered for token in ("date", "time", "timestamp", "year", "month")):
        return "tabular_timeseries_dataset"
    return "tabular_dataset"


def _infer_license_guess(source_url: str, page_title: str | None) -> str | None:
    text = f"{source_url} {page_title or ''}".lower()
    if "huggingface.co" in text:
        return "Unknown (check dataset card / repository metadata)"
    if "github.com" in text or "raw.githubusercontent.com" in text:
        return "Unknown (check repository license)"
    return None


def _infer_publisher(source_url: str) -> str | None:
    hostname = urllib.parse.urlparse(source_url).hostname or ""
    if hostname.endswith("huggingface.co"):
        return "Hugging Face"
    if hostname.endswith("githubusercontent.com") or hostname.endswith("github.com"):
        return "GitHub-hosted source"
    if hostname:
        return hostname.removeprefix("www.")
    return None


def _sample_quality_score(headers: list[str], rows: list[dict[str, Any]]) -> float:
    if not headers or not rows:
        return 0.0
    non_empty_cells = 0
    total_cells = 0
    for row in rows:
        for header in headers:
            total_cells += 1
            value = row.get(header)
            if value not in (None, "", "nan", "NaN"):
                non_empty_cells += 1
    density = non_empty_cells / total_cells if total_cells else 0.0
    width_bonus = min(len(headers) / 10.0, 0.2)
    row_bonus = min(len(rows) / 5.0, 0.1)
    return max(0.0, min(1.0, density * 0.7 + width_bonus + row_bonus))


def _heuristic_validation_result(
    *,
    source_url: str,
    page_title: str | None,
    csv_url: str,
    headers: list[str],
    rows: list[dict[str, Any]],
    llm_failure_reason: str | None = None,
) -> AIValidationResult:
    mappings = _infer_header_mappings(headers, DEFAULT_TARGET_SCHEMA)
    quality = _sample_quality_score(headers, rows)
    if len(headers) < 2 or not rows:
        reject_reasons = ["Deterministic fallback rejected the CSV because it has too few headers or no sample rows."]
        if llm_failure_reason:
            reject_reasons.append(f"LLM unavailable: {llm_failure_reason}")
        return AIValidationResult.model_validate(
            {
                "pass": False,
                "confidence": max(0.0, min(0.4, quality)),
                "resource_type": None,
                "field_mappings": [],
                "summary": "CSV rejected by deterministic fallback validation.",
                "license_guess": _infer_license_guess(source_url, page_title),
                "recommended_title": None,
                "reject_reasons": reject_reasons,
            }
        )
    summary = "Validated by deterministic fallback because LLM validation was unavailable."
    if llm_failure_reason:
        summary = f"{summary} LLM issue: {llm_failure_reason}"
    return AIValidationResult.model_validate(
        {
            "pass": True,
            "confidence": max(0.45, quality),
            "resource_type": _infer_resource_type(headers, rows),
            "field_mappings": mappings,
            "summary": summary,
            "license_guess": _infer_license_guess(source_url, page_title),
            "recommended_title": (page_title or Path(urllib.parse.urlparse(csv_url).path).stem or "CSV resource").strip(),
            "reject_reasons": [],
        }
    )


def _heuristic_draft(
    *,
    source_url: str,
    page_title: str | None,
    csv_url: str,
    headers: list[str],
    rows: list[dict[str, Any]],
    validation_result: AIValidationResult,
    llm_failure_reason: str | None = None,
) -> DatasheetDraftModel:
    title = validation_result.recommended_title or (page_title or Path(urllib.parse.urlparse(csv_url).path).stem or "CSV resource")
    top_headers = headers[:8]
    notes = [
        f"Headers sampled: {', '.join(top_headers)}" if top_headers else "Headers sampled from CSV.",
        "Draft generated via deterministic fallback.",
    ]
    if llm_failure_reason:
        notes.append(f"LLM unavailable during draft generation: {llm_failure_reason}")
    subjects = list(dict.fromkeys([token for header in headers[:10] for token in list(_tokenize_header(header))[:2]]))[:8]
    return DatasheetDraftModel.model_validate(
        {
            "title": title,
            "description": (
                f"CSV resource discovered from {page_title or source_url}. "
                f"The sample contains {len(headers)} headers and {len(rows)} preview rows."
            ),
            "resource_type": validation_result.resource_type or "tabular_dataset",
            "creators": [],
            "subjects": subjects,
            "publisher": _infer_publisher(source_url),
            "license_guess": validation_result.license_guess,
            "potential_uses": [
                "Initial admin review of externally discovered tabular data.",
                "Schema inspection and downstream PATRA resource curation.",
            ],
            "related_download_url": csv_url,
            "sample_notes": notes,
        }
    )


def _validation_prompt(
    *,
    target_schema: dict[str, Any],
    page_title: str | None,
    source_url: str,
    csv_url: str,
    headers: list[str],
    rows: list[dict[str, Any]],
) -> str:
    return (
        "Evaluate whether the CSV sample is a legitimate dataset/resource candidate for PATRA.\n"
        "Reject logs, corrupted files, mostly-garbage exports, or unrelated operational traces.\n\n"
        f"PATRA target schema definition:\n{json.dumps(target_schema, indent=2)}\n\n"
        f"Source page title: {page_title or 'Unknown'}\n"
        f"Source page URL: {source_url}\n"
        f"CSV URL: {csv_url}\n"
        f"CSV headers: {json.dumps(headers)}\n"
        f"CSV sample rows: {json.dumps(rows, indent=2)}\n\n"
        "Return only the validation JSON."
    )


def _draft_prompt(
    *,
    page_title: str | None,
    source_url: str,
    csv_url: str,
    headers: list[str],
    rows: list[dict[str, Any]],
    validation_result: AIValidationResult,
) -> str:
    return (
        "Create a concise PATRA Datasheet Resource draft from the CSV and page context.\n"
        "Base the draft only on observable evidence from the page title, URL, headers, and sample rows.\n"
        "Do not invent unavailable facts. If a field is uncertain, keep it generic.\n\n"
        f"Source page title: {page_title or 'Unknown'}\n"
        f"Source page URL: {source_url}\n"
        f"CSV URL: {csv_url}\n"
        f"Headers: {json.dumps(headers)}\n"
        f"Rows: {json.dumps(rows, indent=2)}\n"
        f"Validation result: {json.dumps(validation_result.model_dump(by_alias=True), indent=2)}\n\n"
        "Return only the datasheet draft JSON."
    )


def _is_probably_csv_url(url: str) -> bool:
    parsed = urllib.parse.urlparse(url)
    path = parsed.path.lower()
    return path.endswith(".csv") or ".csv" in url.lower()


def _parse_huggingface_dataset_id(url: str) -> str | None:
    parsed = urllib.parse.urlparse(url)
    if (parsed.hostname or "").lower() != "huggingface.co":
        return None
    parts = [part for part in parsed.path.split("/") if part]
    if len(parts) < 3 or parts[0] != "datasets":
        return None
    return f"{parts[1]}/{parts[2]}"


def _huggingface_resolve_url(dataset_id: str, path: str) -> str:
    encoded_parts = [urllib.parse.quote(part, safe="") for part in dataset_id.split("/")]
    encoded_path = "/".join(urllib.parse.quote(part, safe="") for part in path.split("/"))
    return f"https://huggingface.co/datasets/{'/'.join(encoded_parts)}/resolve/main/{encoded_path}"


async def _fetch_huggingface_csv_links(url: str) -> tuple[str | None, list[str]]:
    dataset_id = _parse_huggingface_dataset_id(url)
    if not dataset_id:
        return None, []
    dataset_api = f"https://huggingface.co/api/datasets/{dataset_id}"
    tree_api = f"https://huggingface.co/api/datasets/{dataset_id}/tree/main?recursive=true"
    async with httpx.AsyncClient(follow_redirects=True, timeout=30.0) as client:
        info_response = await client.get(dataset_api)
        info_response.raise_for_status()
        info_payload = info_response.json()
        tree_response = await client.get(tree_api)
        tree_response.raise_for_status()
        tree_payload = tree_response.json()

    page_title = info_payload.get("id") or dataset_id
    csv_urls: list[str] = []

    for sibling in info_payload.get("siblings", []) or []:
        path = sibling.get("rfilename")
        if isinstance(path, str) and path.lower().endswith(".csv"):
            csv_urls.append(_huggingface_resolve_url(dataset_id, path))

    for entry in tree_payload or []:
        path = entry.get("path")
        entry_type = entry.get("type")
        if entry_type == "file" and isinstance(path, str) and path.lower().endswith(".csv"):
            csv_urls.append(_huggingface_resolve_url(dataset_id, path))

    return page_title, list(dict.fromkeys(csv_urls))


async def _fetch_html_and_csv_links(url: str) -> tuple[str | None, list[str]]:
    hf_title, hf_csv_urls = await _fetch_huggingface_csv_links(url)
    if hf_csv_urls:
        return hf_title, hf_csv_urls
    async with httpx.AsyncClient(follow_redirects=True, timeout=30.0) as client:
        response = await client.get(url)
        response.raise_for_status()
        parser = CsvLinkParser(str(response.url))
        parser.feed(response.text)
        csv_urls = list(dict.fromkeys(parser.csv_urls))
        return parser.page_title or None, csv_urls


async def _stream_download_csv(url: str, temp_dir: Path) -> Path:
    parsed = urllib.parse.urlparse(url)
    filename = Path(parsed.path).name or f"download-{uuid.uuid4().hex}.csv"
    destination = temp_dir / filename
    async with httpx.AsyncClient(follow_redirects=True, timeout=60.0) as client:
        async with client.stream("GET", url) as response:
            response.raise_for_status()
            content_length = response.headers.get("Content-Length")
            if content_length:
                declared = int(content_length)
                if declared < MIN_FILE_BYTES:
                    raise ValueError(f"CSV rejected: Content-Length {declared} < {MIN_FILE_BYTES}")
                if declared > MAX_FILE_BYTES:
                    raise ValueError(f"CSV rejected: Content-Length {declared} > {MAX_FILE_BYTES}")
            total = 0
            with destination.open("wb") as handle:
                async for chunk in response.aiter_bytes():
                    if not chunk:
                        continue
                    total += len(chunk)
                    if total > MAX_FILE_BYTES:
                        raise ValueError(f"CSV rejected: streamed size exceeded {MAX_FILE_BYTES}")
                    handle.write(chunk)
    size = destination.stat().st_size
    if size < MIN_FILE_BYTES:
        raise ValueError(f"CSV rejected: file size {size} < {MIN_FILE_BYTES}")
    return destination


def _read_csv_preview(path: Path) -> tuple[list[str], list[dict[str, Any]]]:
    df = pd.read_csv(path, nrows=5)
    headers = [str(column).strip() for column in df.columns.tolist() if str(column).strip()]
    if not headers:
        raise ValueError("CSV rejected: no valid headers found")
    records = json.loads(df.fillna("").to_json(orient="records"))
    return headers, records


def _prepare_staging_paths(job_id: int, csv_url: str) -> tuple[Path, Path]:
    suffix = Path(urllib.parse.urlparse(csv_url).path).suffix or ".csv"
    stem = Path(urllib.parse.urlparse(csv_url).path).stem or "dataset"
    safe_stem = "".join(ch if ch.isalnum() or ch in {"-", "_"} else "_" for ch in stem)[:80] or "dataset"
    job_dir = INGESTION_STAGING_DIR / str(job_id)
    job_dir.mkdir(parents=True, exist_ok=True)
    unique = uuid.uuid4().hex[:8]
    csv_path = job_dir / f"{safe_stem}-{unique}{suffix}"
    schema_path = job_dir / f"{safe_stem}-{unique}.json"
    return csv_path, schema_path


async def _process_candidate_csv(
    conn: asyncpg.Connection,
    *,
    job_id: int,
    source_url: str,
    page_title: str | None,
    csv_url: str,
    requested_by: str | None,
    failures: list[str],
) -> bool:
    with tempfile.TemporaryDirectory(prefix="patra-ingestion-") as tmp:
        temp_dir = Path(tmp)
        try:
            downloaded = await _stream_download_csv(csv_url, temp_dir)
            headers, rows = await asyncio.to_thread(_read_csv_preview, downloaded)
            llm_validation_failure: str | None = None
            llm_draft_failure: str | None = None
            validation: AIValidationResult
            if INGESTION_LLM_ENABLED:
                try:
                    validation_payload = await asyncio.to_thread(
                        _call_llm_json_with_model_fallback,
                        prompt=_validation_prompt(
                            target_schema=DEFAULT_TARGET_SCHEMA,
                            page_title=page_title,
                            source_url=source_url,
                            csv_url=csv_url,
                            headers=headers,
                            rows=rows,
                        ),
                        schema_name="ai_validation_result",
                        schema=_validation_json_schema(),
                        api_base=INGESTION_LLM_API_BASE,
                        model=INGESTION_LLM_MODEL,
                        api_key=INGESTION_LLM_API_KEY,
                    )
                    validation = AIValidationResult.model_validate(validation_payload)
                except Exception as exc:  # noqa: BLE001
                    llm_validation_failure = str(exc)
                    if not INGESTION_LLM_FALLBACK_TO_CODE:
                        raise
                    validation = _heuristic_validation_result(
                        source_url=source_url,
                        page_title=page_title,
                        csv_url=csv_url,
                        headers=headers,
                        rows=rows,
                        llm_failure_reason=llm_validation_failure,
                    )
            else:
                validation = _heuristic_validation_result(
                    source_url=source_url,
                    page_title=page_title,
                    csv_url=csv_url,
                    headers=headers,
                    rows=rows,
                    llm_failure_reason="LLM validation disabled by configuration.",
                )
            if not validation.pass_:
                reason = "; ".join(validation.reject_reasons) or validation.summary
                failures.append(f"{csv_url}: {reason}")
                return False
            if INGESTION_LLM_ENABLED:
                try:
                    draft_payload = await asyncio.to_thread(
                        _call_llm_json_with_model_fallback,
                        prompt=_draft_prompt(
                            page_title=page_title,
                            source_url=source_url,
                            csv_url=csv_url,
                            headers=headers,
                            rows=rows,
                            validation_result=validation,
                        ),
                        schema_name="datasheet_draft",
                        schema=_draft_json_schema(),
                        api_base=INGESTION_LLM_API_BASE,
                        model=INGESTION_LLM_MODEL,
                        api_key=INGESTION_LLM_API_KEY,
                    )
                    draft = DatasheetDraftModel.model_validate(draft_payload)
                except Exception as exc:  # noqa: BLE001
                    llm_draft_failure = str(exc)
                    if not INGESTION_LLM_FALLBACK_TO_CODE:
                        raise
                    draft = _heuristic_draft(
                        source_url=source_url,
                        page_title=page_title,
                        csv_url=csv_url,
                        headers=headers,
                        rows=rows,
                        validation_result=validation,
                        llm_failure_reason=llm_draft_failure or llm_validation_failure,
                    )
            else:
                draft = _heuristic_draft(
                    source_url=source_url,
                    page_title=page_title,
                    csv_url=csv_url,
                    headers=headers,
                    rows=rows,
                    validation_result=validation,
                    llm_failure_reason="LLM draft generation disabled by configuration.",
                )
            staged_csv_path, staged_schema_path = _prepare_staging_paths(job_id, csv_url)
            staged_csv_path.write_bytes(downloaded.read_bytes())
            staged_schema_path.write_text(
                json.dumps(
                    {
                        "validation_result": validation.model_dump(by_alias=True),
                        "datasheet_draft": draft.model_dump(),
                        "headers_sample": headers,
                        "rows_sample": rows,
                    },
                    indent=2,
                ),
                encoding="utf-8",
            )
            await _insert_artifact(
                conn,
                job_id=job_id,
                source_url=source_url,
                page_title=page_title,
                csv_url=csv_url,
                headers_sample=headers,
                rows_sample=rows,
                validation_result=validation,
                datasheet_draft=draft,
                staged_csv_path=str(staged_csv_path),
                staged_schema_path=str(staged_schema_path),
                created_by=requested_by,
            )
            return True
        except (ParserError, UnicodeDecodeError, ValueError, httpx.HTTPError, json.JSONDecodeError) as exc:
            failures.append(f"{csv_url}: {exc}")
            return False
        except Exception as exc:  # noqa: BLE001
            log.exception("Unexpected automated ingestion failure for %s", csv_url)
            failures.append(f"{csv_url}: {exc}")
            return False


async def _run_scrape_job(pool: asyncpg.Pool, job_id: int, source_url: str, requested_by: str | None) -> None:
    failures: list[str] = []
    created_artifact_count = 0
    processed_csv_count = 0
    discovered_csv_urls: list[str] = []
    try:
        INGESTION_STAGING_DIR.mkdir(parents=True, exist_ok=True)
        async with pool.acquire() as conn:
            await _update_job(conn, job_id, status="Crawling")

        if _is_probably_csv_url(source_url):
            page_title = Path(urllib.parse.urlparse(source_url).path).name or "CSV resource"
            discovered_csv_urls = [source_url]
        else:
            page_title, discovered_csv_urls = await _fetch_html_and_csv_links(source_url)

        async with pool.acquire() as conn:
            await _update_job(
                conn,
                job_id,
                page_title=page_title,
                discovered_csv_urls=discovered_csv_urls,
                discovered_csv_count=len(discovered_csv_urls),
                status="AI_Validating" if discovered_csv_urls else "Failed",
                error_message="No CSV links discovered on the source page." if not discovered_csv_urls else None,
                recent_failures=failures,
                completed=not discovered_csv_urls,
            )
        if not discovered_csv_urls:
            return

        for csv_url in discovered_csv_urls:
            processed_csv_count += 1
            async with pool.acquire() as conn:
                passed = await _process_candidate_csv(
                    conn,
                    job_id=job_id,
                    source_url=source_url,
                    page_title=page_title,
                    csv_url=csv_url,
                    requested_by=requested_by,
                    failures=failures,
                )
            if passed:
                created_artifact_count += 1
            async with pool.acquire() as conn:
                await _update_job(
                    conn,
                    job_id,
                    processed_csv_count=processed_csv_count,
                    passed_csv_count=created_artifact_count,
                    created_artifact_count=created_artifact_count,
                    recent_failures=failures[-10:],
                )

        final_status = "Completed" if created_artifact_count > 0 else "Failed"
        final_error = None if created_artifact_count > 0 else "No CSV candidates passed validation."
        async with pool.acquire() as conn:
            await _update_job(
                conn,
                job_id,
                status=final_status,
                processed_csv_count=processed_csv_count,
                passed_csv_count=created_artifact_count,
                created_artifact_count=created_artifact_count,
                recent_failures=failures[-10:],
                error_message=final_error,
                completed=True,
            )
    except Exception as exc:  # noqa: BLE001
        log.exception("Automated ingestion job %s failed", job_id)
        async with pool.acquire() as conn:
            await _update_job(
                conn,
                job_id,
                status="Failed",
                error_message=str(exc),
                recent_failures=(failures + [str(exc)])[-10:],
                completed=True,
            )
    finally:
        ACTIVE_INGESTION_TASKS.pop(job_id, None)


def _track_task(job_id: int, task: asyncio.Task) -> None:
    ACTIVE_INGESTION_TASKS[job_id] = task
    task.add_done_callback(lambda _: ACTIVE_INGESTION_TASKS.pop(job_id, None))


@router.post("/scrape", response_model=ScraperJobSummary)
async def start_scrape_job(
    payload: ScrapeRequest,
    actor=Depends(require_admin_actor),
    pool: asyncpg.Pool = Depends(get_pool),
):
    async with pool.acquire() as conn:
        job_id = await _insert_job(conn, str(payload.url), actor.username)
        row = await conn.fetchrow("SELECT * FROM scraper_jobs WHERE id = $1", job_id)
    task = asyncio.create_task(_run_scrape_job(pool, job_id, str(payload.url), actor.username), name=f"automated-ingestion-{job_id}")
    _track_task(job_id, task)
    return ScraperJobSummary.model_validate(_job_row_to_model(row).model_dump())


@router.get("/jobs", response_model=list[ScraperJobSummary])
async def list_scrape_jobs(
    actor=Depends(require_admin_actor),
    pool: asyncpg.Pool = Depends(get_pool),
    limit: int = Query(default=20, ge=1, le=100),
):
    async with pool.acquire() as conn:
        await _ensure_tables(conn)
        rows = await conn.fetch("SELECT * FROM scraper_jobs ORDER BY created_at DESC, id DESC LIMIT $1", limit)
    return [ScraperJobSummary.model_validate(_job_row_to_model(row).model_dump()) for row in rows]


@router.get("/jobs/{job_id}", response_model=ScraperJobDetail)
async def get_scrape_job(
    job_id: int = ApiPath(..., ge=1),
    actor=Depends(require_admin_actor),
    pool: asyncpg.Pool = Depends(get_pool),
):
    async with pool.acquire() as conn:
        job = await _fetch_job(conn, job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Ingestion job not found")
    return job


@router.get("/artifacts", response_model=list[IngestionArtifactSummary])
async def list_ingestion_artifacts(
    actor=Depends(require_admin_actor),
    pool: asyncpg.Pool = Depends(get_pool),
    status_filter: str | None = Query(default=None, alias="status"),
    limit: int = Query(default=50, ge=1, le=200),
):
    params: list[Any] = []
    where = ""
    if status_filter:
        where = "WHERE status = $1"
        params.append(status_filter)
    params.append(limit)
    async with pool.acquire() as conn:
        await _ensure_tables(conn)
        rows = await conn.fetch(
            f"""
            SELECT *
            FROM automated_ingestion_artifacts
            {where}
            ORDER BY created_at DESC, id DESC
            LIMIT ${len(params)}
            """,
            *params,
        )
    return [_artifact_row_to_summary(row) for row in rows]


@router.get("/artifacts/{artifact_id}", response_model=IngestionArtifactDetail)
async def get_ingestion_artifact(
    artifact_id: int = ApiPath(..., ge=1),
    actor=Depends(require_admin_actor),
    pool: asyncpg.Pool = Depends(get_pool),
):
    async with pool.acquire() as conn:
        await _ensure_tables(conn)
        row = await conn.fetchrow("SELECT * FROM automated_ingestion_artifacts WHERE id = $1", artifact_id)
    if not row:
        raise HTTPException(status_code=404, detail="Ingestion artifact not found")
    return _artifact_row_to_detail(row)


@router.put("/artifacts/{artifact_id}/review", response_model=IngestionArtifactDetail)
async def review_ingestion_artifact(
    payload: ArtifactReviewRequest,
    artifact_id: int = ApiPath(..., ge=1),
    actor=Depends(require_admin_actor),
    pool: asyncpg.Pool = Depends(get_pool),
):
    async with pool.acquire() as conn:
        await _ensure_tables(conn)
        row = await conn.fetchrow(
            """
            UPDATE automated_ingestion_artifacts
            SET status = $2,
                reviewed_by = $3,
                reviewed_at = NOW(),
                review_notes = $4,
                updated_at = NOW()
            WHERE id = $1
            RETURNING *
            """,
            artifact_id,
            payload.status,
            actor.username,
            payload.review_notes,
        )
    if not row:
        raise HTTPException(status_code=404, detail="Ingestion artifact not found")
    return _artifact_row_to_detail(row)


@router.get("/artifacts/{artifact_id}/download.csv")
async def download_ingestion_csv(
    artifact_id: int = ApiPath(..., ge=1),
    actor=Depends(require_admin_actor),
    pool: asyncpg.Pool = Depends(get_pool),
):
    async with pool.acquire() as conn:
        await _ensure_tables(conn)
        row = await conn.fetchrow(
            "SELECT staged_csv_path, datasheet_draft FROM automated_ingestion_artifacts WHERE id = $1",
            artifact_id,
        )
    if not row:
        raise HTTPException(status_code=404, detail="Ingestion artifact not found")
    path = Path(row["staged_csv_path"])
    if not path.exists():
        raise HTTPException(status_code=404, detail="Staged CSV file not found")
    filename = f"{(_decode_json_column(row['datasheet_draft']) or {}).get('title', 'resource')}.csv"
    return FileResponse(path, media_type="text/csv", filename=filename)


@router.get("/artifacts/{artifact_id}/download-schema")
async def download_ingestion_schema(
    artifact_id: int = ApiPath(..., ge=1),
    actor=Depends(require_admin_actor),
    pool: asyncpg.Pool = Depends(get_pool),
):
    async with pool.acquire() as conn:
        await _ensure_tables(conn)
        row = await conn.fetchrow(
            "SELECT staged_schema_path, datasheet_draft FROM automated_ingestion_artifacts WHERE id = $1",
            artifact_id,
        )
    if not row:
        raise HTTPException(status_code=404, detail="Ingestion artifact not found")
    path = Path(row["staged_schema_path"])
    if not path.exists():
        raise HTTPException(status_code=404, detail="Staged schema file not found")
    filename = f"{(_decode_json_column(row['datasheet_draft']) or {}).get('title', 'resource')}.json"
    return FileResponse(path, media_type="application/json", filename=filename)
